# Generated by Django 6.0.6 on 2026-06-06 06:28

import django.db.models.deletion
import sismat.models.courses
import sismat.models.students
import sismat.models.teachers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
                ('names', models.CharField(db_column='names', max_length=100)),
                ('fatherSurname', models.CharField(db_column='fathersurname', max_length=100)),
                ('motherSurname', models.CharField(db_column='mothersurname', max_length=100)),
                ('specialty', models.CharField(blank=True, db_column='specialty', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True, validators=[sismat.models.teachers.validate_phone_format])),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(db_column='email', max_length=150, unique=True)),
                ('passwordHash', models.TextField(db_column='passwordhash')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], db_column='role', default='student', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_column='status', default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
                ('courseName', models.CharField(db_column='coursename', max_length=150)),
                ('credits', models.IntegerField(db_column='credits', validators=[sismat.models.courses.validate_positive_credits])),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('teacher_id', models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sismat.teachers')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sismat.users'),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
                ('names', models.CharField(db_column='names', max_length=100)),
                ('fatherSurname', models.CharField(db_column='fathersurname', max_length=100)),
                ('motherSurname', models.CharField(db_column='mothersurname', max_length=100)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=20, null=True, validators=[sismat.models.students.validate_min_phone_digits])),
                ('note', models.TextField(blank=True, db_column='note', null=True)),
                ('user_id', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sismat.users')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='CoursesStudents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.UUIDField(blank=True, null=True)),
                ('modified_id', models.UUIDField(blank=True, null=True)),
                ('enrollmentDate', models.DateTimeField(auto_now_add=True, db_column='enrollmentdate')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='sismat.courses')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='sismat.students')),
            ],
            options={
                'verbose_name_plural': 'Courses Students',
                'db_table': 'courses_students',
                'unique_together': {('course', 'student')},
            },
        ),
    ]
